version: "3"

networks:
  laravel-redis-horizon:
    driver: bridge

services:
  laravel-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    restart: unless-stopped
    tty: true
    expose:
      - "9000:9000"
    volumes:
      - .:/var/www/app
    networks:
      - laravel-redis-horizon

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7000:80"
    volumes:
      - ./.config/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    depends_on:
      - laravel-php
      - laravel-mysql
      - laravel-redis
    networks:
      - laravel-redis-horizon

  laravel-mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: docker_mysql_password
      MYSQL_DATABASE: laravel_redis_horizon
      MYSQL_USER: faidfadjri
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-redis-horizon

  laravel-redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    networks:
      - laravel-redis-horizon

volumes:
  mysql_data:
